"""Hybrid Stacking meta-learner."""

import logging
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import polars as pl
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression, Ridge, Lasso, ElasticNet

from thesis.config.loader import Config
from thesis.models.lstm_model import SequenceClassifier, _resolve_device

logger = logging.getLogger("thesis.models")


def train_stacking(config: Config) -> None:
    """Train and persist the stacking meta-learner.

    Loads **out-of-fold** predictions generated on the training set by each
    base model, fits the configured meta-learner on those OOF predictions,
    optionally calibrates probabilities, and saves filtered confidence-aware
    predictions for downstream evaluation.

    The meta-learner is trained exclusively on OOF (out-of-fold) predictions
    from the training period — never on validation or test data.  This
    eliminates the information leakage that would occur if validation
    predictions were used for meta-learner training.

    Args:
        config: Loaded application configuration.
    """
    logger.info("Loading OOF predictions from training set...")

    # Load OOF predictions (generated by generate_lightgbm_oof / generate_lstm_oof)
    lgbm_oof_path = Path(config.models["tree"].oof_predictions_path)
    lstm_oof_path = Path(config.models["lstm"].oof_predictions_path)

    if not lgbm_oof_path.exists():
        raise FileNotFoundError(
            f"LightGBM OOF predictions not found: {lgbm_oof_path}. "
            "Run generate_lightgbm_oof() first."
        )
    if not lstm_oof_path.exists():
        raise FileNotFoundError(
            f"LSTM OOF predictions not found: {lstm_oof_path}. "
            "Run generate_lstm_oof() first."
        )

    lgbm_oof = pl.read_parquet(lgbm_oof_path)
    lstm_oof = pl.read_parquet(lstm_oof_path)

    # Align OOF predictions by timestamp
    logger.info(f"LightGBM OOF predictions: {len(lgbm_oof)} samples")
    logger.info(f"LSTM OOF predictions: {len(lstm_oof)} samples")

    # Normalize timestamp dtypes to microseconds for consistent join
    lgbm_oof = lgbm_oof.with_columns(pl.col("timestamp").cast(pl.Datetime("us")))
    lstm_oof = lstm_oof.with_columns(pl.col("timestamp").cast(pl.Datetime("us")))

    # Join on timestamp to ensure alignment
    aligned = lgbm_oof.join(lstm_oof, on="timestamp", suffix="_lstm")

    logger.info(f"Aligned OOF predictions: {len(aligned)} samples")

    if len(aligned) == 0:
        raise ValueError(
            "No matching timestamps found between LightGBM and LSTM OOF predictions."
        )

    # Create meta-features (6 features: 3 classes × 2 models)
    logger.info("Creating meta-features from OOF predictions...")

    # LightGBM probabilities
    lgbm_proba = aligned.select(
        [
            "pred_proba_class_minus1",
            "pred_proba_class_0",
            "pred_proba_class_1",
        ]
    ).to_numpy()

    # LSTM probabilities (with suffix from join)
    lstm_proba = aligned.select(
        [
            "pred_proba_class_minus1_lstm",
            "pred_proba_class_0_lstm",
            "pred_proba_class_1_lstm",
        ]
    ).to_numpy()

    # Concatenate
    X_meta = np.hstack([lgbm_proba, lstm_proba])

    # Labels (use LightGBM's true_label since they should be the same)
    y = aligned["true_label"].to_numpy()

    logger.info(f"Meta-feature shape: {X_meta.shape}")
    logger.info(
        f"Meta-learner training on OOF predictions from TRAINING set only "
        f"({len(y)} samples) — no leakage from val/test"
    )

    # Train meta-learner
    meta_learner_type = config.models["stacking"].meta_learner
    logger.info(f"Training meta-learner: {meta_learner_type}")

    model: Any
    if meta_learner_type == "logistic_regression":
        model = LogisticRegression(
            C=config.models["stacking"].C,
            max_iter=1000,
            random_state=config.workflow.random_seed,
        )
    elif meta_learner_type == "ridge":
        model = Ridge(alpha=config.models["stacking"].alpha)
    elif meta_learner_type == "lasso":
        model = Lasso(alpha=config.models["stacking"].alpha)
    elif meta_learner_type == "elastic_net":
        model = ElasticNet(
            alpha=config.models["stacking"].alpha,
            l1_ratio=config.models["stacking"].l1_ratio,
        )
    elif meta_learner_type == "lightgbm":
        try:
            import lightgbm as lgb

            cfg = config.models["stacking"]
            model = lgb.LGBMClassifier(
                n_estimators=cfg.n_estimators,
                learning_rate=cfg.learning_rate,
                objective="multiclass",
                num_class=3,
                random_state=config.workflow.random_seed,
            )
        except ImportError:
            raise ImportError("LightGBM not installed")
    else:
        raise ValueError(f"Unknown meta-learner: {meta_learner_type}")

    model.fit(X_meta, y)

    # Probability calibration (if enabled)
    # Note: cv=5 uses K-Fold (not time-aware), but this is acceptable because
    # (a) all data is from the training set (no val/test leakage), and
    # (b) calibration is a monotonic transform on probabilities from a simple
    #     LogisticRegression whose outputs are already well-calibrated.
    if config.models["stacking"].calibrate_probabilities:
        logger.info(
            f"Calibrating probabilities using {config.models['stacking'].calibration_method}"
        )

        if config.models["stacking"].calibration_method == "isotonic":
            calibrated = CalibratedClassifierCV(model, method="isotonic", cv=5)
        else:  # Platt scaling
            calibrated = CalibratedClassifierCV(model, method="sigmoid", cv=5)

        calibrated.fit(X_meta, y)
        model = calibrated

    # Save meta-learner
    model_path = Path(config.models["stacking"].model_path)
    model_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, model_path)
    logger.info(f"Saved meta-learner: {model_path}")

    # Generate training-set predictions (diagnostic — shows meta-learner fit quality)
    logger.info("Generating stacking predictions on OOF data (diagnostic)...")

    # Confidence threshold: only predict when max probability >= 0.6
    confidence_threshold = 0.6

    predict_proba_fn = getattr(model, "predict_proba", None)
    if callable(predict_proba_fn):
        probs_raw: Any = predict_proba_fn(X_meta)
        if hasattr(probs_raw, "toarray"):
            probs_raw = probs_raw.toarray()
        probs = np.asarray(probs_raw, dtype=float)
    else:
        # For regression-based meta-learners, convert to probabilities
        preds = np.asarray(model.predict(X_meta))
        probs = np.zeros((len(preds), 3), dtype=float)
        for i, p in enumerate(preds):
            idx = int(p) + 1  # Map -1,0,1 to 0,1,2
            idx = max(0, min(2, idx))
            probs[i, idx] = 1.0

    # Apply confidence threshold: low confidence -> Hold (class 0)
    max_probs = np.max(probs, axis=1)
    low_confidence_mask = max_probs < confidence_threshold

    # Log confidence statistics
    n_low_conf = np.sum(low_confidence_mask)
    logger.info(
        f"Confidence threshold ({confidence_threshold}): {n_low_conf}/{len(probs)} "
        f"({100 * n_low_conf / len(probs):.1f}%) predictions set to Hold (low confidence)"
    )

    # Create final predictions with confidence filtering
    final_preds = np.argmax(probs, axis=1) - 1  # Convert 0,1,2 to -1,0,1
    final_preds[low_confidence_mask] = 0  # Set low confidence to Hold (0)

    # Update probabilities for low confidence cases: set Hold=1.0, others=0.0
    probs_filtered = probs.copy()
    probs_filtered[low_confidence_mask, :] = 0.0
    probs_filtered[low_confidence_mask, 1] = 1.0  # Class 0 (Hold) is index 1

    # Save predictions
    preds_df = pl.DataFrame(
        {
            "pred_proba_class_minus1": probs[:, 0],
            "pred_proba_class_0": probs[:, 1],
            "pred_proba_class_1": probs[:, 2],
        }
    )

    preds_path = Path(config.models["stacking"].meta_predictions_path)
    preds_path.parent.mkdir(parents=True, exist_ok=True)
    preds_df.write_parquet(preds_path)
    logger.info(f"Saved stacking predictions: {preds_path}")


def generate_test_predictions(config: Config) -> None:
    """Generate test set predictions for backtesting.

    Loads trained LightGBM, LSTM, and meta-learner models,
    generates predictions on test data, and saves final stacking predictions.

    Args:
        config: Configuration object.
    """
    import pandas as pd
    import torch

    logger.info("Generating test set predictions for backtest...")

    # Load test data
    test_path = Path(config.paths.test_data)
    if not test_path.exists():
        raise FileNotFoundError(f"Test data not found: {test_path}")

    test_df = pl.read_parquet(test_path)
    logger.info(f"Loaded test data: {len(test_df)} samples")

    # Get feature columns (same logic as in training)
    exclude_cols = [
        "timestamp",
        "label",
        "tp_price",
        "sl_price",
        "touched_bar",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "avg_spread",
        "tick_count",
    ]
    feature_cols = [c for c in test_df.columns if c not in exclude_cols]

    # ============ LightGBM Predictions ============
    logger.info("Generating LightGBM predictions on test set...")
    lgbm_path = Path(config.models["tree"].model_path)
    if not lgbm_path.exists():
        raise FileNotFoundError(f"LightGBM model not found: {lgbm_path}")

    lgbm_model = joblib.load(lgbm_path)

    # Prepare test features
    X_test = test_df.select(feature_cols).to_numpy()
    X_test_df = pd.DataFrame(X_test, columns=feature_cols)

    # Generate predictions
    lgbm_probs = lgbm_model.predict_proba(X_test_df)
    if hasattr(lgbm_probs, "toarray"):
        lgbm_probs = lgbm_probs.toarray()

    lgbm_preds_df = pl.DataFrame(
        {
            "timestamp": test_df["timestamp"],
            "pred_proba_class_minus1": lgbm_probs[:, 0],  # Short
            "pred_proba_class_0": lgbm_probs[:, 1],  # Hold
            "pred_proba_class_1": lgbm_probs[:, 2],  # Long
        }
    )
    logger.info(f"LightGBM test predictions: {len(lgbm_preds_df)} samples")

    # ============ LSTM Predictions ============
    logger.info("Generating LSTM predictions on test set...")
    lstm_path = Path(config.models["lstm"].model_path)
    if not lstm_path.exists():
        raise FileNotFoundError(f"LSTM model not found: {lstm_path}")

    # LSTM uses only OHLCV features - same as training
    ohlcv_cols = ["open", "high", "low", "close", "volume"]
    seq_length = config.models["lstm"].sequence_length
    features = test_df.select(ohlcv_cols).to_numpy()

    # Load training normalization statistics (use training stats to prevent data leakage)
    stats_path = Path(config.models["lstm"].model_path).parent / "lstm_norm_stats.npz"
    if not stats_path.exists():
        raise FileNotFoundError(
            f"LSTM normalization stats not found: {stats_path}. Run training first."
        )

    stats = np.load(stats_path)
    train_means = stats["means"]
    train_stds = stats["stds"]

    # Normalize using TRAINING statistics (not test data statistics)
    features = (features - train_means) / train_stds
    logger.info(
        f"Loaded LSTM normalization stats from training: means={train_means.round(2)}, stds={train_stds.round(2)}"
    )

    # Create sequences
    X_test_lstm = []
    for i in range(len(features) - seq_length):
        X_test_lstm.append(features[i : i + seq_length])
    X_test_lstm = np.array(X_test_lstm)

    # Load LSTM/GRU model
    device = _resolve_device(config.models["lstm"].device)

    # Model parameters (must match training)
    model_type = config.models["lstm"].model_type
    input_size = len(ohlcv_cols)  # 5 features
    hidden_size = config.models["lstm"].hidden_size
    num_layers = config.models["lstm"].num_layers
    dropout = config.models["lstm"].dropout
    bidirectional = config.models["lstm"].bidirectional
    num_classes = 3

    lstm_model = SequenceClassifier(
        input_size=input_size,
        hidden_size=hidden_size,
        num_layers=num_layers,
        num_classes=num_classes,
        dropout=dropout,
        bidirectional=bidirectional,
        model_type=model_type,
    )
    lstm_model.load_state_dict(torch.load(lstm_path, map_location=device))
    lstm_model.to(device)
    lstm_model.eval()

    # Generate predictions
    with torch.no_grad():
        X_test_tensor = torch.FloatTensor(X_test_lstm).to(device)
        outputs = lstm_model(X_test_tensor)
        lstm_probs = torch.softmax(outputs, dim=1).cpu().numpy()

    # Get timestamps aligned with sequences (seq_length offset)
    timestamps_lstm = test_df["timestamp"].to_numpy()[seq_length:]

    lstm_preds_df = pl.DataFrame(
        {
            "timestamp": timestamps_lstm,
            "pred_proba_class_minus1_lstm": lstm_probs[:, 0],  # Short
            "pred_proba_class_0_lstm": lstm_probs[:, 1],  # Hold
            "pred_proba_class_1_lstm": lstm_probs[:, 2],  # Long
        }
    )

    # Normalize timestamp dtypes to microseconds for consistent join
    lstm_preds_df = lstm_preds_df.with_columns(
        pl.col("timestamp").cast(pl.Datetime("us"))
    )

    logger.info(f"LSTM test predictions: {len(lstm_preds_df)} samples")

    logger.info("Generating stacking predictions on test set...")
    meta_path = Path(config.models["stacking"].model_path)
    if not meta_path.exists():
        raise FileNotFoundError(f"Meta-learner not found: {meta_path}")

    meta_learner = joblib.load(meta_path)

    # Align predictions by timestamp (normalize dtypes first)
    lgbm_preds_df = lgbm_preds_df.with_columns(
        pl.col("timestamp").cast(pl.Datetime("us"))
    )
    aligned = lgbm_preds_df.join(lstm_preds_df, on="timestamp", suffix="_lstm")
    logger.info(f"Aligned test predictions: {len(aligned)} samples")
    if len(aligned) != len(test_df):
        logger.info(
            "Skipped %s warm-up bars before stacking because LSTM uses %s-bar sequences",
            len(test_df) - len(aligned),
            seq_length,
        )

    if len(aligned) == 0:
        raise ValueError(
            "No matching timestamps found between LightGBM and LSTM test predictions."
        )

    # Create meta-features (same as in training)
    X_meta = np.hstack(
        [
            aligned[
                ["pred_proba_class_minus1", "pred_proba_class_0", "pred_proba_class_1"]
            ].to_numpy(),
            aligned[
                [
                    "pred_proba_class_minus1_lstm",
                    "pred_proba_class_0_lstm",
                    "pred_proba_class_1_lstm",
                ]
            ].to_numpy(),
        ]
    )

    # Generate stacking predictions
    if hasattr(meta_learner, "predict_proba"):
        final_probs = meta_learner.predict_proba(X_meta)
    else:
        preds = meta_learner.predict(X_meta)
        final_probs = np.zeros((len(preds), 3))
        for i, p in enumerate(preds):
            idx = int(p) + 1
            idx = max(0, min(2, idx))
            final_probs[i, idx] = 1.0

    # Apply confidence threshold: 0.6 minimum confidence
    confidence_threshold = 0.6
    max_probs = np.max(final_probs, axis=1)
    low_confidence_mask = max_probs < confidence_threshold

    # Log confidence statistics
    n_low_conf = np.sum(low_confidence_mask)
    logger.info(
        f"Confidence threshold ({confidence_threshold}): {n_low_conf}/{len(final_probs)} "
        f"({100 * n_low_conf / len(final_probs):.1f}%) predictions set to Hold (low confidence)"
    )

    # Set low confidence predictions to Hold (class 0)
    final_preds = np.argmax(final_probs, axis=1)
    final_preds[low_confidence_mask] = 1  # Index 1 = Hold (class 0)

    # Update probabilities for low confidence cases
    final_probs_filtered = final_probs.copy()
    final_probs_filtered[low_confidence_mask, :] = 0.0
    final_probs_filtered[low_confidence_mask, 1] = 1.0  # Set Hold prob to 1.0

    # Save final predictions
    final_preds_df = pl.DataFrame(
        {
            "timestamp": aligned["timestamp"],
            "pred_proba_class_minus1": final_probs_filtered[:, 0],  # Short
            "pred_proba_class_0": final_probs_filtered[:, 1],  # Hold
            "pred_proba_class_1": final_probs_filtered[:, 2],  # Long
        }
    )

    final_path = Path(config.paths.final_predictions)
    final_path.parent.mkdir(parents=True, exist_ok=True)
    final_preds_df.write_parquet(final_path)
    logger.info(f"Saved final test predictions: {final_path}")
    logger.info(f"Total test predictions: {len(final_preds_df)} samples")


def apply_confidence_threshold(
    predictions: np.ndarray, probabilities: np.ndarray, threshold: float = 0.6
) -> tuple[np.ndarray, np.ndarray]:
    """Apply confidence threshold to predictions.

    Predictions with max probability below threshold are converted to Hold (0).

    Args:
        predictions: Array of predicted labels (-1, 0, 1)
        probabilities: Array of probability distributions (n_samples, n_classes)
        threshold: Minimum confidence threshold (default 0.6)

    Returns:
        Tuple of (filtered_predictions, filtered_probabilities)
    """
    # Create copies to avoid modifying inputs
    filtered_preds = predictions.copy()
    filtered_probs = probabilities.copy()

    # Calculate max probability for each prediction
    max_probs = np.max(probabilities, axis=1)

    # Find low confidence predictions
    low_conf_mask = max_probs < threshold

    # Convert low confidence predictions to Hold (class 0)
    filtered_preds[low_conf_mask] = 0

    # Update probabilities: set Hold probability to 1.0 for low confidence
    filtered_probs[low_conf_mask, :] = 0.0
    # Assuming Hold is at index 1 (classes: -1=index 0, 0=index 1, 1=index 2)
    if filtered_probs.shape[1] >= 2:
        filtered_probs[low_conf_mask, 1] = 1.0

    return filtered_preds, filtered_probs
